# Generated by Django 4.2.10 on 2025-04-17 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicioIngesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "ultima_verificacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última verificación"
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado en"),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="servicios_modificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicio_ingesta",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio de Ingesta",
                "verbose_name_plural": "Servicios de Ingesta",
            },
        ),
        migrations.CreateModel(
            name="ReglaFiltrado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "campo",
                    models.CharField(
                        choices=[
                            ("ASUNTO", "Asunto"),
                            ("REMITENTE", "Remitente"),
                            ("DESTINATARIO", "Destinatario"),
                            ("CONTENIDO", "Contenido"),
                            ("ADJUNTO", "Nombre de adjunto"),
                        ],
                        default="ASUNTO",
                        max_length=20,
                        verbose_name="Campo",
                    ),
                ),
                (
                    "condicion",
                    models.CharField(
                        choices=[
                            ("CONTIENE", "Contiene"),
                            ("NO_CONTIENE", "No contiene"),
                            ("ES_IGUAL", "Es igual a"),
                            ("EMPIEZA_CON", "Empieza con"),
                            ("TERMINA_CON", "Termina con"),
                            ("COINCIDE_REGEX", "Coincide con regex"),
                        ],
                        default="CONTIENE",
                        max_length=20,
                        verbose_name="Condición",
                    ),
                ),
                ("valor", models.CharField(max_length=255, verbose_name="Valor")),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("PROCESAR", "Procesar"),
                            ("IGNORAR", "Ignorar"),
                            ("ARCHIVAR", "Archivar"),
                            ("ETIQUETAR", "Etiquetar"),
                        ],
                        default="PROCESAR",
                        max_length=20,
                        verbose_name="Acción",
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "prioridad",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Prioridad"
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado en"),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reglas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas",
                        to="ingesta_correo.servicioingesta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de Filtrado",
                "verbose_name_plural": "Reglas de Filtrado",
                "ordering": ["prioridad", "creado_en"],
            },
        ),
        migrations.CreateModel(
            name="CorreoIngesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mensaje_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="ID del mensaje"
                    ),
                ),
                (
                    "remitente",
                    models.CharField(max_length=255, verbose_name="Remitente"),
                ),
                ("destinatarios", models.TextField(verbose_name="Destinatarios")),
                ("asunto", models.CharField(max_length=255, verbose_name="Asunto")),
                (
                    "fecha_recepcion",
                    models.DateTimeField(verbose_name="Fecha de recepción"),
                ),
                (
                    "contenido_plano",
                    models.TextField(
                        blank=True, null=True, verbose_name="Contenido texto plano"
                    ),
                ),
                (
                    "contenido_html",
                    models.TextField(
                        blank=True, null=True, verbose_name="Contenido HTML"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PROCESADO", "Procesado"),
                            ("ERROR", "Error"),
                            ("IGNORADO", "Ignorado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_procesamiento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de procesamiento"
                    ),
                ),
                (
                    "mensaje_error",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensaje de error"
                    ),
                ),
                (
                    "marcado_leido",
                    models.BooleanField(
                        default=False, verbose_name="Marcado como leído"
                    ),
                ),
                (
                    "glosas_extraidas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Glosas extraídas"
                    ),
                ),
                (
                    "intentos_procesamiento",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Intentos de procesamiento"
                    ),
                ),
                (
                    "evento",
                    models.CharField(
                        default="Correo recibido", max_length=100, verbose_name="Evento"
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado en"),
                ),
                (
                    "regla_aplicada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="correos_procesados",
                        to="ingesta_correo.reglafiltrado",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correos",
                        to="ingesta_correo.servicioingesta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Correo Ingesta",
                "verbose_name_plural": "Correos Ingesta",
                "ordering": ["-fecha_recepcion"],
            },
        ),
        migrations.CreateModel(
            name="ArchivoAdjunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_archivo",
                    models.CharField(max_length=255, verbose_name="Nombre del archivo"),
                ),
                (
                    "tipo_contenido",
                    models.CharField(max_length=100, verbose_name="Tipo de contenido"),
                ),
                ("tamaño", models.PositiveIntegerField(verbose_name="Tamaño en bytes")),
                (
                    "archivo",
                    models.FileField(
                        upload_to="correos/adjuntos/%Y/%m/%d/", verbose_name="Archivo"
                    ),
                ),
                (
                    "procesado",
                    models.BooleanField(default=False, verbose_name="Procesado"),
                ),
                (
                    "fecha_procesamiento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de procesamiento"
                    ),
                ),
                (
                    "resultado_procesamiento",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Resultado del procesamiento",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "correo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjuntos",
                        to="ingesta_correo.correoingesta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo Adjunto",
                "verbose_name_plural": "Archivos Adjuntos",
            },
        ),
        migrations.CreateModel(
            name="LogActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_hora",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha/Hora"),
                ),
                (
                    "evento",
                    models.CharField(
                        choices=[
                            ("CORREO_RECIBIDO", "Correo recibido"),
                            ("ADJUNTO_EXTRAIDO", "Adjunto extraído"),
                            ("GLOSA_PROCESADA", "Glosa procesada"),
                            ("ERROR_PROCESAMIENTO", "Error de procesamiento"),
                            ("SERVICIO_INICIADO", "Servicio iniciado"),
                            ("SERVICIO_DETENIDO", "Servicio detenido"),
                            ("REGLA_CREADA", "Regla creada"),
                            ("REGLA_MODIFICADA", "Regla modificada"),
                            ("REGLA_ELIMINADA", "Regla eliminada"),
                        ],
                        max_length=30,
                        verbose_name="Evento",
                    ),
                ),
                ("detalles", models.TextField(verbose_name="Detalles")),
                (
                    "estado",
                    models.CharField(default="", max_length=20, verbose_name="Estado"),
                ),
                (
                    "correo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="ingesta_correo.correoingesta",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs_ingesta",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_ingesta",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Actividad",
                "verbose_name_plural": "Logs de Actividad",
                "ordering": ["-fecha_hora"],
                "indexes": [
                    models.Index(
                        fields=["-fecha_hora"], name="ingesta_cor_fecha_h_cca479_idx"
                    ),
                    models.Index(
                        fields=["evento"], name="ingesta_cor_evento_c32766_idx"
                    ),
                    models.Index(
                        fields=["tenant"], name="ingesta_cor_tenant__c4d896_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EstadisticaDiaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                (
                    "correos_procesados",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Correos procesados"
                    ),
                ),
                (
                    "glosas_extraidas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Glosas extraídas"
                    ),
                ),
                (
                    "pendientes",
                    models.PositiveIntegerField(default=0, verbose_name="Pendientes"),
                ),
                (
                    "errores",
                    models.PositiveIntegerField(default=0, verbose_name="Errores"),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estadisticas_ingesta",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estadística Diaria",
                "verbose_name_plural": "Estadísticas Diarias",
                "ordering": ["-fecha"],
                "unique_together": {("tenant", "fecha")},
            },
        ),
        migrations.AddIndex(
            model_name="correoingesta",
            index=models.Index(
                fields=["mensaje_id"], name="ingesta_cor_mensaje_1e9e94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="correoingesta",
            index=models.Index(
                fields=["remitente"], name="ingesta_cor_remiten_9fb61e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="correoingesta",
            index=models.Index(fields=["asunto"], name="ingesta_cor_asunto_1db06b_idx"),
        ),
        migrations.AddIndex(
            model_name="correoingesta",
            index=models.Index(fields=["estado"], name="ingesta_cor_estado_6e931d_idx"),
        ),
        migrations.AddIndex(
            model_name="correoingesta",
            index=models.Index(
                fields=["fecha_recepcion"], name="ingesta_cor_fecha_r_3149ad_idx"
            ),
        ),
    ]
