# Generated by Django 4.2.10 on 2025-04-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="correo_contacto",
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name="Correo de contacto"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="direccion",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Dirección"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="nit",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="NIT"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="telefono",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Teléfono"
            ),
        ),
    ]
