# Generated by Django 4.2.10 on 2025-04-17 04:01

import apps.configuracion.models
import apps.core.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "tenants",
            "0003_alter_tenant_correo_contacto_alter_tenant_direccion_and_more",
        ),
        ("configuracion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantconfig",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.core.storage.TenantFileSystemStorage(),
                upload_to=apps.configuracion.models.tenant_directory_path,
                verbose_name="Logo del cliente",
            ),
        ),
        migrations.CreateModel(
            name="EmailOAuthCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(max_length=255, verbose_name="Client ID"),
                ),
                (
                    "client_secret",
                    models.CharField(max_length=255, verbose_name="Client Secret"),
                ),
                (
                    "redirect_uri",
                    models.CharField(max_length=255, verbose_name="URI de Redirección"),
                ),
                (
                    "email_address",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Dirección de Correo Monitoreada",
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True, null=True, verbose_name="Token de Acceso"
                    ),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        blank=True, null=True, verbose_name="Token de Actualización"
                    ),
                ),
                (
                    "token_expiry",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expiración del Token"
                    ),
                ),
                (
                    "authorized",
                    models.BooleanField(default=False, verbose_name="Autorizado"),
                ),
                (
                    "last_authorized",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última Autorización"
                    ),
                ),
                (
                    "folder_to_monitor",
                    models.CharField(
                        default="INBOX",
                        max_length=100,
                        verbose_name="Carpeta a Monitorear",
                    ),
                ),
                (
                    "check_interval",
                    models.IntegerField(
                        default=5, verbose_name="Intervalo de Verificación (minutos)"
                    ),
                ),
                (
                    "mark_as_read",
                    models.BooleanField(default=True, verbose_name="Marcar como Leído"),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_credentials",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credenciales OAuth para Correo",
                "verbose_name_plural": "Credenciales OAuth para Correo",
            },
        ),
    ]
