# Generated by Django 4.2.10 on 2025-04-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenant_correo_contacto_tenant_direccion_tenant_nit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="correo_contacto",
            field=models.EmailField(max_length=255, verbose_name="Correo de contacto"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="direccion",
            field=models.CharField(max_length=255, verbose_name="Dirección"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="nit",
            field=models.CharField(max_length=20, verbose_name="NIT"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="telefono",
            field=models.CharField(max_length=20, verbose_name="Teléfono"),
        ),
    ]
