# Generated by Django 4.2.10 on 2025-04-17 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuracion", "0002_alter_tenantconfig_logo_emailoauthcredentials"),
        ("configuracion", "0003_emailoauthcredentials_ingesta_enabled"),
    ]

    operations = []
